SELECT tgt.DEATHDATE as DEATHDATE, tgt.HEALTHCARE_EXPENSES as HEALTHCARE_EXPENSES,
tgt.SUFFIX as SUFFIX, tgt.PASSPORT as PASSPORT, tgt.CITY as CITY, tgt.BIRTHPLACE as BIRTHPLACE,
tgt.MAIDEN as MAIDEN, tgt.MARITAL as MARITAL, tgt.DRIVERS as DRIVERS, tgt.STATE as STATE, tgt.COUNTY as
COUNTY, tgt.ADDRESS as ADDRESS, tgt.PREFIX as PREFIX, tgt.ZIP as ZIP, tgt.LON as LON, tgt.SSN as SSN, tgt.LAST
as LAST, tgt.BIRTHDATE as BIRTHDATE, tgt.RACE as RACE, tgt.ETHNICITY as ETHNICITY, tgt.GENDER as
GENDER, tgt.id as id, tgt.HEALTHCARE_COVERAGE as HEALTHCARE_COVERAGE, tgt.LAT as LAT, tgt.FIRST as
FIRST FROM curatedpatients tgt