export const DummyData = [
    {
        id: 1,
        test: 'testcase28_manual_sql_notifications',
        rowsource: '01',
        rowtarget: '02',
        rowmatched: '02',
        rowmismatched: '0',
        runtime: '00:01:31',
        result: 'Passed',
        reason: 'Content Matched',
        date: "xyz",
        createDate: '21 Jan 2023',

    },
    {
        id: 2,
        test: 'testcase28_manual_sql_notifications',
        rowsource: '01',
        rowtarget: '02',
        rowmatched: '02',
        rowmismatched: '0',
        runtime: '00:01:31',
        result: 'Failed',
        reason: 'Content Mismatched',
        date: "xyz",
        createDate: '21 Jan 2023',
    },
    {
        id: 3,
        test: 'testcase28_manual_sql_notifications',
        rowsource: '01',
        rowtarget: '02',
        rowmatched: '02',
        rowmismatched: '0',
        runtime: '00:01:31',
        result: 'Passed',
        reason: 'Content Matched',
        date: "xyz",
        createDate: '21 Jan 2023',
    },
    {
        id: 4,
        test: 'testcase28_manual_sql_notifications',
        rowsource: '01',
        rowtarget: '02',
        rowmatched: '02',
        rowmismatched: '0',
        runtime: '00:01:31',
        result: 'Passed',
        reason: 'Content Matched',
        date: "xyz",
        createDate: '21 Jan 2023',

    },
    {
        id: 5,
        test: 'testcase28_manual_sql_notifications',
        rowsource: '01',
        rowtarget: '02',
        rowmatched: '02',
        rowmismatched: '0',
        runtime: '00:01:31',
        result: 'Failed',
        reason: 'Content Mismatched',
        date: "xyz",
        createDate: '21 Jan 2023',

    },
    {
        id: 6,
        test: 'testcase28_manual_sql_notifications',
        rowsource: '01',
        rowtarget: '02',
        rowmatched: '02',
        rowmismatched: '0',
        runtime: '00:01:31',
        result: 'Passed',
        reason: 'Content Matched',
        date: "xyz",
        createDate: '21 Jan 2023',

    }, {
        id: 7,
        test: 'testcase28_manual_sql_notifications',
        rowsource: '01',
        rowtarget: '02',
        rowmatched: '02',
        rowmismatched: '0',
        runtime: '00:01:31',
        result: 'Passed',
        reason: 'Content Matched',
        date: "xyz",
        createDate: '21 Jan 2023',

    },
    {
        id: 8,
        test: 'testcase28_manual_sql_notifications',
        rowsource: '01',
        rowtarget: '02',
        rowmatched: '02',
        rowmismatched: '0',
        runtime: '00:01:31',
        result: 'Passed',
        reason: 'Content Matched',
        date: "xyz",
        createDate: '21 Jan 2023',

    }, {
        id: 9,
        test: 'testcase28_manual_sql_notifications',
        rowsource: '01',
        rowtarget: '02',
        rowmatched: '02',
        rowmismatched: '0',
        runtime: '00:01:31',
        result: 'Passed',
        reason: 'Content Matched',
        date: "xyz",
        createDate: '21 Jan 2023',

    }, {
        id: 10,
        test: 'testcase28_manual_sql_notifications',
        rowsource: '01',
        rowtarget: '02',
        rowmatched: '02',
        rowmismatched: '0',
        runtime: '00:01:31',
        result: 'Passed',
        reason: 'Content Matched',
        date: "xyz",
        createDate: '21 Jan 2023',

    }, {
        id: 11,
        test: 'testcase28_manual_sql_notifications',
        rowsource: '01',
        rowtarget: '02',
        rowmatched: '02',
        rowmismatched: '0',
        runtime: '00:01:31',
        result: 'Passed',
        reason: 'Content Matched',
        date: "xyz",
        createDate: '21 Jan 2023',

    }, {
        id: 12,
        test: 'testcase28_manual_sql_notifications',
        rowsource: '01',
        rowtarget: '02',
        rowmatched: '02',
        rowmismatched: '0',
        runtime: '00:01:31',
        result: 'Passed',
        reason: 'Content Matched',
        date: "xyz",
        createDate: '21 Jan 2023',

    },

]

export const SecondTable = [
    {
        id: 1,
        name: 'Demo_protocol_123',
        version: '01',
        environment: 'Dev',
        test_cases: '02',
        runtime: '00:01:31',
        passed_test: '01',
        failed_test: '01',
        connection: 's3',
        filepath: '/app/test/results/',
        app_name: 'Sample',
        date: 'xyz'

    },
    {
        id: 2,
        name: 'Demo_protocol_123',
        version: '01',
        environment: 'Dev',
        test_cases: '02',
        runtime: '00:01:31',
        passed_test: '01',
        failed_test: '01',
        connection: 's3',
        filepath: '/app/test/results/',
        app_name: 'Sample',
        date: 'xyz'

    },
    {
        id: 3,
        name: 'Demo_protocol_123',
        version: '01',
        environment: 'Dev',
        test_cases: '02',
        runtime: '00:01:31',
        passed_test: '01',
        failed_test: '01',
        connection: 's3',
        filepath: '/app/test/results/',
        app_name: 'Sample',
        date: 'xyz'

    },
    {
        id: 4,
        name: 'Demo_protocol_123',
        version: '01',
        environment: 'Dev',
        test_cases: '02',
        runtime: '00:01:31',
        passed_test: '01',
        failed_test: '01',
        connection: 's3',
        filepath: '/app/test/results/',
        app_name: 'Sample',
        date: 'xyz'

    },
    {
        id: 5,
        name: 'Demo_protocol_123',
        version: '01',
        environment: 'Dev',
        test_cases: '02',
        runtime: '00:01:31',
        passed_test: '01',
        failed_test: '01',
        connection: 's3',
        filepath: '/app/test/results/',
        app_name: 'Sample',
        date: 'xyz'

    },
    {
        id: 6,
        name: 'Demo_protocol_123',
        version: '01',
        environment: 'Dev',
        test_cases: '02',
        runtime: '00:01:31',
        passed_test: '01',
        failed_test: '01',
        connection: 's3',
        filepath: '/app/test/results/',
        app_name: 'Sample',
        date: 'xyz'

    },
    {
        id: 7,
        name: 'Demo_protocol_123',
        version: '01',
        environment: 'Dev',
        test_cases: '02',
        runtime: '00:01:31',
        passed_test: '01',
        failed_test: '01',
        connection: 's3',
        filepath: '/app/test/results/',
        app_name: 'Sample',
        date: 'xyz'

    },
    {
        id: 8,
        name: 'Demo_protocol_123',
        version: '01',
        environment: 'Dev',
        test_cases: '02',
        runtime: '00:01:31',
        passed_test: '01',
        failed_test: '01',
        connection: 's3',
        filepath: '/app/test/results/',
        app_name: 'Sample',
        date: 'xyz'

    },
    {
        id: 9,
        name: 'Demo_protocol_123',
        version: '01',
        environment: 'Dev',
        test_cases: '02',
        runtime: '00:01:31',
        passed_test: '01',
        failed_test: '01',
        connection: 's3',
        filepath: '/app/test/results/',
        app_name: 'Sample',
        date: 'xyz'

    },
    {
        id: 10,
        name: 'Demo_protocol_123',
        version: '01',
        environment: 'Dev',
        test_cases: '02',
        runtime: '00:01:31',
        passed_test: '01',
        failed_test: '01',
        connection: 's3',
        filepath: '/app/test/results/',
        app_name: 'Sample',
        date: 'xyz'

    },
    {
        id: 11,
        name: 'Demo_protocol_123',
        version: '01',
        environment: 'Dev',
        test_cases: '02',
        runtime: '00:01:31',
        passed_test: '01',
        failed_test: '01',
        connection: 's3',
        filepath: '/app/test/results/',
        app_name: 'Sample',
        date: 'xyz'

    },
    {
        id: 12,
        name: 'Demo_protocol_123',
        version: '01',
        environment: 'Dev',
        test_cases: '02',
        runtime: '00:01:31',
        passed_test: '01',
        failed_test: '01',
        connection: 's3',
        filepath: '/app/test/results/',
        app_name: 'Sample',
        date: 'xyz'

    },
    {
        id: 13,
        name: 'Demo_protocol_123',
        version: '01',
        environment: 'Dev',
        test_cases: '02',
        runtime: '00:01:31',
        passed_test: '01',
        failed_test: '01',
        connection: 's3',
        filepath: '/app/test/results/',
        app_name: 'Sample',
        date: 'xyz'

    },

]

export const ConnectionData = [
    {
        id: 1,
        connection: 'raw_mysql_database_Connection',
        createDate: '21 Jan 2023',
        date: "xyz"

    },
    {
        id: 2,
        connection: 'raw_mysql_database_Connection',
        createDate: '21 Jan 2023',
        date: "xyz"

    },
    {
        id: 3,
        connection: 'raw_mysql_database_Connection',
        createDate: '21 Jan 2023',
        date: "xyz"

    },
    {
        id: 4,
        connection: 'raw_mysql_database_Connection',
        createDate: '21 Jan 2023',
        date: "xyz"

    },
    {
        id: 5,
        connection: 'raw_mysql_database_Connection',
        createDate: '21 Jan 2023',
        date: "xyz"

    },
    {
        id: 6,
        connection: 'raw_mysql_database_Connection',
        createDate: '21 Jan 2023',
        date: "xyz"

    },
    {
        id: 7,
        connection: 'raw_mysql_database_Connection',
        createDate: '21 Jan 2023',
        date: "xyz"

    },
    {
        id: 8,
        connection: 'raw_mysql_database_Connection',
        createDate: '21 Jan 2023',
        date: "xyz"

    },
    {
        id: 9,
        connection: 'raw_mysql_database_Connection',
        createDate: '21 Jan 2023',
        date: "xyz"

    },
    {
        id: 10,
        connection: 'raw_mysql_database_Connection',
        createDate: '21 Jan 2023',
        date: "xyz"

    },

]

export const DBData = [{
    id: 1,
    name: 'testcase28_manual_sql_notification',
    path: "/app/test/testcases/testcase1_parquet_mismatch.xlsx",
    date: 'xyz'
},
{
    id: 2,
    name: 'testcase28_manual_sql_notification',
    path: "/app/test/testcases/testcase1_parquet_mismatch.xlsx",
    date: 'xyz'
},
{
    id: 3,
    name: 'testcase28_manual_sql_notification',
    path: "/app/test/testcases/testcase1_parquet_mismatch.xlsx",
    date: 'xyz'
},
{
    id: 4,
    name: 'testcase28_manual_sql_notification',
    path: "/app/test/testcases/testcase1_parquet_mismatch.xlsx",
    date: 'xyz'
},
{
    id: 5,
    name: 'testcase28_manual_sql_notification',
    path: "/app/test/testcases/testcase1_parquet_mismatch.xlsx",
    date: 'xyz'
},
{
    id: 6,
    name: 'testcase28_manual_sql_notification',
    path: "/app/test/testcases/testcase1_parquet_mismatch.xlsx",
    date: 'xyz'
},
{
    id: 7,
    name: 'testcase28_manual_sql_notification',
    path: "/app/test/testcases/testcase1_parquet_mismatch.xlsx",
    date: 'xyz'
},
{
    id: 8,
    name: 'testcase28_manual_sql_notification',
    path: "/app/test/testcases/testcase1_parquet_mismatch.xlsx",
    date: 'xyz'
},
{
    id: 9,
    name: 'testcase28_manual_sql_notification',
    path: "/app/test/testcases/testcase1_parquet_mismatch.xlsx",
    date: 'xyz'
},
{
    id: 10,
    name: 'testcase28_manual_sql_notification',
    path: "/app/test/testcases/testcase1_parquet_mismatch.xlsx",
    date: 'xyz'
}]

export const connectData = [{
    "connnectiontype": "jdbcdatabase",
    "connectname": "raw_jdbcdatabase_connection",
    "host": "lifesciencedemodb.ctpjbleh0qtd.us-east-1.rds.amazonaws.com",
    "port": "3306",
    "database": "patients_db",
    "user": "admin",
    "password": "myadmin1234"
}]

export const Mappingactive2 = [
    {
    id:1,
    Tgt_Table_Type : "Stage",
    Tgt_Table_Name: "StageData",
    Tgt_Column_Name: "ID",
    Src_Table_Type :'Source',
    Src_Table_Name:'Sourcedata',
    Src_Column_Name:'id',
    Transformation_Type:'Direct mapped',
    filterout_nulls:'String',
    select_sql_expression:'String',
    filter_sql_expression:'String',
    lookup_table_name:'String',
    lookup_column_name:'String',
    lookup_return_expression:'String',
    remove_duplicate_partition:'String',
    remove_duplicate_order:'String',
    remove_duplicate_order_type:'String',
},
{
    id:2,
    Tgt_Table_Type : "Stage",
    Tgt_Table_Name: "StageData",
    Tgt_Column_Name: "ID",
    Src_Table_Type :'Source',
    Src_Table_Name:'Sourcedata',
    Src_Column_Name:'id',
    Transformation_Type:'Direct mapped',
    filterout_nulls:'String',
    select_sql_expression:'String',
    filter_sql_expression:'String',
    lookup_table_name:'String',
    lookup_column_name:'String',
    lookup_return_expression:'String',
    remove_duplicate_partition:'String',
    remove_duplicate_order:'String',
    remove_duplicate_order_type:'String',
},
{
    id:3,
    Tgt_Table_Type : "Stage",
    Tgt_Table_Name: "StageData",
    Tgt_Column_Name: "ID",
    Src_Table_Type :'Source',
    Src_Table_Name:'Sourcedata',
    Src_Column_Name:'id',
    Transformation_Type:'Direct mapped',
    filterout_nulls:'String',
    select_sql_expression:'String',
    filter_sql_expression:'String',
    lookup_table_name:'String',
    lookup_column_name:'String',
    lookup_return_expression:'String',
    remove_duplicate_partition:'String',
    remove_duplicate_order:'String',
    remove_duplicate_order_type:'String',
},
{
    id:4,
    Tgt_Table_Type : "Stage",
    Tgt_Table_Name: "StageData",
    Tgt_Column_Name: "ID",
    Src_Table_Type :'Source',
    Src_Table_Name:'Sourcedata',
    Src_Column_Name:'id',
    Transformation_Type:'Direct mapped',
    filterout_nulls:'String',
    select_sql_expression:'String',
    filter_sql_expression:'String',
    lookup_table_name:'String',
    lookup_column_name:'String',
    lookup_return_expression:'String',
    remove_duplicate_partition:'String',
    remove_duplicate_order:'String',
    remove_duplicate_order_type:'String',
},
{
    id:5,
    Tgt_Table_Type : "Stage",
    Tgt_Table_Name: "StageData",
    Tgt_Column_Name: "ID",
    Src_Table_Type :'Source',
    Src_Table_Name:'Sourcedata',
    Src_Column_Name:'id',
    Transformation_Type:'Direct mapped',
    filterout_nulls:'String',
    select_sql_expression:'String',
    filter_sql_expression:'String',
    lookup_table_name:'String',
    lookup_column_name:'String',
    lookup_return_expression:'String',
    remove_duplicate_partition:'String',
    remove_duplicate_order:'String',
    remove_duplicate_order_type:'String',
},
{
    id:6,
    Tgt_Table_Type : "Stage",
    Tgt_Table_Name: "StageData",
    Tgt_Column_Name: "ID",
    Src_Table_Type :'Source',
    Src_Table_Name:'Sourcedata',
    Src_Column_Name:'id',
    Transformation_Type:'Direct mapped',
    filterout_nulls:'String',
    select_sql_expression:'String',
    filter_sql_expression:'String',
    lookup_table_name:'String',
    lookup_column_name:'String',
    lookup_return_expression:'String',
    remove_duplicate_partition:'String',
    remove_duplicate_order:'String',
    remove_duplicate_order_type:'String',
},
{
    id:7,
    Tgt_Table_Type : "Stage",
    Tgt_Table_Name: "StageData",
    Tgt_Column_Name: "ID",
    Src_Table_Type :'Source',
    Src_Table_Name:'Sourcedata',
    Src_Column_Name:'id',
    Transformation_Type:'Direct mapped',
    filterout_nulls:'String',
    select_sql_expression:'String',
    filter_sql_expression:'String',
    lookup_table_name:'String',
    lookup_column_name:'String',
    lookup_return_expression:'String',
    remove_duplicate_partition:'String',
    remove_duplicate_order:'String',
    remove_duplicate_order_type:'String',
},
{
    id:8,
    Tgt_Table_Type : "Stage",
    Tgt_Table_Name: "StageData",
    Tgt_Column_Name: "ID",
    Src_Table_Type :'Source',
    Src_Table_Name:'Sourcedata',
    Src_Column_Name:'id',
    Transformation_Type:'Direct mapped',
    filterout_nulls:'String',
    select_sql_expression:'String',
    filter_sql_expression:'String',
    lookup_table_name:'String',
    lookup_column_name:'String',
    lookup_return_expression:'String',
    remove_duplicate_partition:'String',
    remove_duplicate_order:'String',
    remove_duplicate_order_type:'String',
},
{
    id:9,
    Tgt_Table_Type : "Stage",
    Tgt_Table_Name: "StageData",
    Tgt_Column_Name: "ID",
    Src_Table_Type :'Source',
    Src_Table_Name:'Sourcedata',
    Src_Column_Name:'id',
    Transformation_Type:'Direct mapped',
    filterout_nulls:'String',
    select_sql_expression:'String',
    filter_sql_expression:'String',
    lookup_table_name:'String',
    lookup_column_name:'String',
    lookup_return_expression:'String',
    remove_duplicate_partition:'String',
    remove_duplicate_order:'String',
    remove_duplicate_order_type:'String',
},
{
    id:10,
    Tgt_Table_Type : "Stage",
    Tgt_Table_Name: "StageData",
    Tgt_Column_Name: "ID",
    Src_Table_Type :'Source',
    Src_Table_Name:'Sourcedata',
    Src_Column_Name:'id',
    Transformation_Type:'Direct mapped',
    filterout_nulls:'String',
    select_sql_expression:'String',
    filter_sql_expression:'String',
    lookup_table_name:'String',
    lookup_column_name:'String',
    lookup_return_expression:'String',
    remove_duplicate_partition:'String',
    remove_duplicate_order:'String',
    remove_duplicate_order_type:'String',
},
{
    id:11,
    Tgt_Table_Type : "Stage",
    Tgt_Table_Name: "StageData",
    Tgt_Column_Name: "ID",
    Src_Table_Type :'Source',
    Src_Table_Name:'Sourcedata',
    Src_Column_Name:'id',
    Transformation_Type:'Direct mapped',
    filterout_nulls:'String',
    select_sql_expression:'String',
    filter_sql_expression:'String',
    lookup_table_name:'String',
    lookup_column_name:'String',
    lookup_return_expression:'String',
    remove_duplicate_partition:'String',
    remove_duplicate_order:'String',
    remove_duplicate_order_type:'String',
},
{
    id:12,
    Tgt_Table_Type : "Stage",
    Tgt_Table_Name: "StageData",
    Tgt_Column_Name: "ID",
    Src_Table_Type :'Source',
    Src_Table_Name:'Sourcedata',
    Src_Column_Name:'id',
    Transformation_Type:'Direct mapped',
    filterout_nulls:'String',
    select_sql_expression:'String',
    filter_sql_expression:'String',
    lookup_table_name:'String',
    lookup_column_name:'String',
    lookup_return_expression:'String',
    remove_duplicate_partition:'String',
    remove_duplicate_order:'String',
    remove_duplicate_order_type:'String',
},
{
    id:13,
    Tgt_Table_Type : "Stage",
    Tgt_Table_Name: "StageData",
    Tgt_Column_Name: "ID",
    Src_Table_Type :'Source',
    Src_Table_Name:'Sourcedata',
    Src_Column_Name:'id',
    Transformation_Type:'Direct mapped',
    filterout_nulls:'String',
    select_sql_expression:'String',
    filter_sql_expression:'String',
    lookup_table_name:'String',
    lookup_column_name:'String',
    lookup_return_expression:'String',
    remove_duplicate_partition:'String',
    remove_duplicate_order:'String',
    remove_duplicate_order_type:'String',
},
{
    id:14,
    Tgt_Table_Type : "Stage",
    Tgt_Table_Name: "StageData",
    Tgt_Column_Name: "ID",
    Src_Table_Type :'Source',
    Src_Table_Name:'Sourcedata',
    Src_Column_Name:'id',
    Transformation_Type:'Direct mapped',
    filterout_nulls:'String',
    select_sql_expression:'String',
    filter_sql_expression:'String',
    lookup_table_name:'String',
    lookup_column_name:'String',
    lookup_return_expression:'String',
    remove_duplicate_partition:'String',
    remove_duplicate_order:'String',
    remove_duplicate_order_type:'String',
},
{
    id:15,
    Tgt_Table_Type : "Stage",
    Tgt_Table_Name: "StageData",
    Tgt_Column_Name: "ID",
    Src_Table_Type :'Source',
    Src_Table_Name:'Sourcedata',
    Src_Column_Name:'id',
    Transformation_Type:'Direct mapped',
    filterout_nulls:'String',
    select_sql_expression:'String',
    filter_sql_expression:'String',
    lookup_table_name:'String',
    lookup_column_name:'String',
    lookup_return_expression:'String',
    remove_duplicate_partition:'String',
    remove_duplicate_order:'String',
    remove_duplicate_order_type:'String',
},
{
    id:16,
    Tgt_Table_Type : "Stage",
    Tgt_Table_Name: "StageData",
    Tgt_Column_Name: "ID",
    Src_Table_Type :'Source',
    Src_Table_Name:'Sourcedata',
    Src_Column_Name:'id',
    Transformation_Type:'Direct mapped',
    filterout_nulls:'String',
    select_sql_expression:'String',
    filter_sql_expression:'String',
    lookup_table_name:'String',
    lookup_column_name:'String',
    lookup_return_expression:'String',
    remove_duplicate_partition:'String',
    remove_duplicate_order:'String',
    remove_duplicate_order_type:'String',
},
{
    id:17,
    Tgt_Table_Type : "Stage",
    Tgt_Table_Name: "StageData",
    Tgt_Column_Name: "ID",
    Src_Table_Type :'Source',
    Src_Table_Name:'Sourcedata',
    Src_Column_Name:'id',
    Transformation_Type:'Direct mapped',
    filterout_nulls:'String',
    select_sql_expression:'String',
    filter_sql_expression:'String',
    lookup_table_name:'String',
    lookup_column_name:'String',
    lookup_return_expression:'String',
    remove_duplicate_partition:'String',
    remove_duplicate_order:'String',
    remove_duplicate_order_type:'String',
},
{
    id:18,
    Tgt_Table_Type : "Stage",
    Tgt_Table_Name: "StageData",
    Tgt_Column_Name: "ID",
    Src_Table_Type :'Source',
    Src_Table_Name:'Sourcedata',
    Src_Column_Name:'id',
    Transformation_Type:'Direct mapped',
    filterout_nulls:'String',
    select_sql_expression:'String',
    filter_sql_expression:'String',
    lookup_table_name:'String',
    lookup_column_name:'String',
    lookup_return_expression:'String',
    remove_duplicate_partition:'String',
    remove_duplicate_order:'String',
    remove_duplicate_order_type:'String',
},
{
    id:19,
    Tgt_Table_Type : "Stage",
    Tgt_Table_Name: "StageData",
    Tgt_Column_Name: "ID",
    Src_Table_Type :'Source',
    Src_Table_Name:'Sourcedata',
    Src_Column_Name:'id',
    Transformation_Type:'Direct mapped',
    filterout_nulls:'String',
    select_sql_expression:'String',
    filter_sql_expression:'String',
    lookup_table_name:'String',
    lookup_column_name:'String',
    lookup_return_expression:'String',
    remove_duplicate_partition:'String',
    remove_duplicate_order:'String',
    remove_duplicate_order_type:'String',
},
{
    id:20,
    Tgt_Table_Type : "Stage",
    Tgt_Table_Name: "StageData",
    Tgt_Column_Name: "ID",
    Src_Table_Type :'Source',
    Src_Table_Name:'Sourcedata',
    Src_Column_Name:'id',
    Transformation_Type:'Direct mapped',
    filterout_nulls:'String',
    select_sql_expression:'String',
    filter_sql_expression:'String',
    lookup_table_name:'String',
    lookup_column_name:'String',
    lookup_return_expression:'String',
    remove_duplicate_partition:'String',
    remove_duplicate_order:'String',
    remove_duplicate_order_type:'String',
},
{
    id:21,
    Tgt_Table_Type : "Stage",
    Tgt_Table_Name: "StageData",
    Tgt_Column_Name: "ID",
    Src_Table_Type :'Source',
    Src_Table_Name:'Sourcedata',
    Src_Column_Name:'id',
    Transformation_Type:'Direct mapped',
    filterout_nulls:'String',
    select_sql_expression:'String',
    filter_sql_expression:'String',
    lookup_table_name:'String',
    lookup_column_name:'String',
    lookup_return_expression:'String',
    remove_duplicate_partition:'String',
    remove_duplicate_order:'String',
    remove_duplicate_order_type:'String',
},
{
    id:22,
    Tgt_Table_Type : "Stage",
    Tgt_Table_Name: "StageData",
    Tgt_Column_Name: "ID",
    Src_Table_Type :'Source',
    Src_Table_Name:'Sourcedata',
    Src_Column_Name:'id',
    Transformation_Type:'Direct mapped',
    filterout_nulls:'String',
    select_sql_expression:'String',
    filter_sql_expression:'String',
    lookup_table_name:'String',
    lookup_column_name:'String',
    lookup_return_expression:'String',
    remove_duplicate_partition:'String',
    remove_duplicate_order:'String',
    remove_duplicate_order_type:'String',
},
{
    id:23,
    Tgt_Table_Type : "Stage",
    Tgt_Table_Name: "StageData",
    Tgt_Column_Name: "ID",
    Src_Table_Type :'Source',
    Src_Table_Name:'Sourcedata',
    Src_Column_Name:'id',
    Transformation_Type:'Direct mapped',
    filterout_nulls:'String',
    select_sql_expression:'String',
    filter_sql_expression:'String',
    lookup_table_name:'String',
    lookup_column_name:'String',
    lookup_return_expression:'String',
    remove_duplicate_partition:'String',
    remove_duplicate_order:'String',
    remove_duplicate_order_type:'String',
},
{
    id:24,
    Tgt_Table_Type : "Stage",
    Tgt_Table_Name: "StageData",
    Tgt_Column_Name: "ID",
    Src_Table_Type :'Source',
    Src_Table_Name:'Sourcedata',
    Src_Column_Name:'id',
    Transformation_Type:'Direct mapped',
    filterout_nulls:'String',
    select_sql_expression:'String',
    filter_sql_expression:'String',
    lookup_table_name:'String',
    lookup_column_name:'String',
    lookup_return_expression:'String',
    remove_duplicate_partition:'String',
    remove_duplicate_order:'String',
    remove_duplicate_order_type:'String',
},
]
