SELECT ID,BIRTHDATE,PREFIX,FIRST,LAST,SUFFIX,GENDER,STATE FROM SAMPLE_SRC_PATIENTS
WHERE EXTRACT(MONTH FROM BIRTHDATE) = EXTRACT(MONTH FROM SYSDATE())
  AND EXTRACT(DAY FROM BIRTHDATE) = EXTRACT(DAY FROM SYSDATE())