SELECT ID,BIRTHDATE,PREFIX,FIRST,LAST,SUFFIX,GENDER,STATE FROM sys.orc_patients_db
WHERE EXTRACT(MONTH FROM BIRTHDATE) = EXTRACT(MONTH FROM SYSDATE)
  AND EXTRACT(DAY FROM BIRTHDATE) = EXTRACT(DAY FROM SYSDATE)