pip install datacompy[spark]
pip install datacompy[fugue]
pip install fpdf
pip install openpyxl
pip install fsspec
pip install pretty-html-table
pip install tabulate
pip install cryptography
pip install streamlit
pip install langchain-openai