# Manually Trigger Github Actions workflow to execute Snowpark code
name: datf_snowpark_edition

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of Validation'
        default: 'count'
        required: true
        type: string
      test_name:
        description: 'Name of Test Cases'
        default: 'all'
        required: true
        type: string
  push:
    branches: [ "datf_snowpark" ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/install.txt
      - name: Test Execution using Snowpark
        run: |
          sh scripts/testingstart.sh ${{ inputs.test_type }} ${{ inputs.test_name }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pdf-reports
          path: "utils/reports"

  report:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: pdf-reports
      - name: List Report Files
        run: |
          echo "Displaying the reports..."
          ls
          mkdir pdfs
      - name: Summary html to pdf
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./datfreport.html
          outputFile: ./pdfs/datfsummary.pdf
          pdfOptions: '{"landscape": true}'
      - name: Trends html to pdf
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./datf_trends_report.html
          outputFile: ./pdfs/datftrends.pdf
      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-reports
          path: ./pdfs

