# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Snowpark DATF

on:
  push:
    branches: [ "datf_snowpark" ]
  pull_request:
    branches: [ "datf_snowpark" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/install.txt
      - name: Test Snowpark
        run: |
          scripts/testingstart.bat $test-type $test-names
